### ISSUE TITLE
Examples on Oculus Quest (original) only displays in left eye

### ISSUE THREAD

**Issue by twoxfh** [diarmidmackenzie/screen-display#3]
Great component, I was reviewing it and started noticing I could not see the a-camera entities in my right eye on my original Oculus Quest using the Examples. Not sure why. Any insight is appreciated, will continue hunting.

**Comment by diarmidmackenzie** [comment]
Hi, the component was intended for use on mobile/desktop devices.

When in "screen" mode, the objects are rendered very small, very close to the camera.

In stereoscopic VR the cameras for each eye are positioned a short distance apart.

I haven't looked at exactly how they get positioned relative to the reference camera.  My expectation would have been that the left eye would be slightly left of center, and the right eye slightly right of center, in which case I would expect the object not to be visible in either eye.

From your description, though, perhaps the left eye is rendered from the reference camera position, and the right eye from a position somewhat to the right of that.

**Comment by twoxfh** [comment]
Going to close issue, the Oculus quest has 2 different displays and you need permission to access the second screen. Very cool component that's geared toward desktop use.
